---
title: "Resume of Qianxuan Huang"
output: 
  html_document:
    toc: true
    toc_float: true

---

### Personal information
Name: Qianxuan Huang <br>
Email: qh2285@cumc.columbia.edu

### Education

**Columbia University Mailman School of Public Health** <br>
Master of Public Health (MPH) Biostatistics | Sept. 2023 – Present <br>

**Technion-Israel Institute of Technology** <br> 
Bachelor of Science (BS) Biotechnology and Food Engineering | Aug. 2019 – Aug. 2023 <br>
Scholarship: Third-Class Chancellor’s Scholarship (2020, 2021, 2022), Second-Class Chancellor’s Scholarship (2019)

### Academic research & data analysis project

* Associations Between Diabetes and Cognitive Impairment in Late Middle-Aged Adults | New York <br>
Apr. 2024 <br>
Individual SAS Course Project <br>

* Survival Analysis of Breast Cancer Patients | Remote <br>
Aug. - Dec. 2022 <br>
Individual Research <br>

* Data Survey of a Chinese Video Platform Called Bilibili | New York <br>
Mar. 2024 <br>
SQL Course Project <br>

### College projects
**Op-ed: A Call for Sex Education in Communities of Color Influencing Adolescent Pregnancy | New York** <br>
Dec. 2023 <br>
Individual Paper



